from enum import Enum


class ContractValidationErrorCodes(str, Enum):
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_VALUE = "INVALID_VALUE"
    DUPLICATE_COLUMN = "DUPLICATE_COLUMN"
    EMPTY_COLUMNS = "EMPTY_COLUMNS"
    UNSUPPORTED_CONTRACT_VERSION = "UNSUPPORTED_CONTRACT_VERSION"