from enum import Enum

class ExecutionErrorCode(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    STEP_FAILED = "STEP_FAILED"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    WRITE_FAILED = "WRITE_FAILED"
    POSTCHECK_FAILED = "POSTCHECK_FAILED"
    UNSUPPORTED_STEP = "UNSUPPORTED_STEP"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    INTERNAL_ERROR = "INTERNAL_ERROR"